// Generated by the gRPC protobuf plugin.
// If you make any local change, they will be lost.
// source: etcdv3_auth.proto
#ifndef GRPC_etcdv3_5fauth_2eproto__INCLUDED
#define GRPC_etcdv3_5fauth_2eproto__INCLUDED

#include "auth.pb.h"

#include <grpc++/impl/codegen/async_stream.h>
#include <grpc++/impl/codegen/async_unary_call.h>
#include <grpc++/impl/codegen/proto_utils.h>
#include <grpc++/impl/codegen/rpc_method.h>
#include <grpc++/impl/codegen/service_type.h>
#include <grpc++/impl/codegen/status.h>
#include <grpc++/impl/codegen/stub_options.h>
#include <grpc++/impl/codegen/sync_stream.h>

namespace grpc {
class CompletionQueue;
class Channel;
class RpcService;
class ServerCompletionQueue;
class ServerContext;
}  // namespace grpc

namespace authpb {

}  // namespace authpb


#endif  // GRPC_etcdv3_5fauth_2eproto__INCLUDED
